[theme]
background = "#eff1f5"
primary = "#4c4f69"
secondary = "#5c5f77"
title = "#8839ef"
playing = "#40a02b"
playing_selected = "#40a02b"
playing_bg = "#ccd0da"
highlight = "#dc8a78"
highlight_bg = "#bcc0cc"
error = "#d20f39"
error_bg = "#eff1f5"
statusbar = "#e6e9ef"
statusbar_progress = "#8839ef"
statusbar_bg = "#ccd0da"
header = "#8839ef"
