[theme]
background = "#24273a"
primary = "#cad3f5"
secondary = "#b8c0e0"
title = "#c6a0f6"
playing = "#a6da95"
playing_selected = "#a6da95"
playing_bg = "#363a4f"
highlight = "#f4dbd6"
highlight_bg = "#494d64"
error = "#ed8796"
error_bg = "#24273a"
statusbar = "#1e2030"
statusbar_progress = "#c6a0f6"
statusbar_bg = "#363a4f"
header = "#c6a0f6"
