[theme]
background = "#1e1e2e"
primary = "#cdd6f4"
secondary = "#bac2de"
title = "#cba6f7"
playing = "#a6e3a1"
playing_selected = "#a6e3a1"
playing_bg = "#313244"
highlight = "#f5e0dc"
highlight_bg = "#45475a"
error = "#f38ba8"
error_bg = "#1e1e2e"
statusbar = "#181825"
statusbar_progress = "#cba6f7"
statusbar_bg = "#313244"
header = "#cba6f7"
