[theme]
background = "#303446"
primary = "#c6d0f5"
secondary = "#b5bfe2"
title = "#ca9ee6"
playing = "#a6d189"
playing_selected = "#a6d189"
playing_bg = "#414559"
highlight = "#f2d5cf"
highlight_bg = "#51576d"
error = "#e78284"
error_bg = "#303446"
statusbar = "#292c3c"
statusbar_progress = "#ca9ee6"
statusbar_bg = "#414559"
header = "#ca9ee6"
